version: '3'
services:

  app:
    image: figured/php-dev:7.2
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  web:
    image: nginx:stable
    working_dir: /var/www
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./:/var/www
    ports:
      - 8080:80

  database:
    image: mysql:5.7
    volumes:
      - mysqldbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"

  mongodb:
    image: mongo:latest
    container_name: "mongodb_figured"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null


volumes:
  mysqldbdata:
  mongodbdata:
